steps:
# Build a Docker Image 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_ARTIFACTS_DIR/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA', '.']

# Image Push to Artifacts Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_ARTIFACTS_DIR/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA']

# Deploy Image to Cloud Run Services
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'aaa-poc'
  - '--image'
  - '$_ARTIFACTS_DIR/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA'
  - '--allow-unauthenticated'
  - '--region'
  - '$_DEPLOY_REGION'
  - '--memory'
  - '$_MEMORY'
  - '--cpu'
  - '$_CPU'
  - '--port'
  - '$_CONTAINER_PORT'
  - '--min-instances'
  - $_MIN_INSTANCES
  - '--max-instances'
  - $_MAX_INSTANCES
  - '--set-env-vars'
  - $_SET_ENV_VARS